#49: Adding unscheduled maintenance endpoint.
ResilienX/fraihmwork-api pull request #50
Opened 2022-05-10 16:01 UTC by MS-ResilienX

2022-05-11 13:13 UTC, GD-ResilienX requested changes
Swagger tidiness issues :(

2022-05-11 13:13 UTC, GD-ResilienX commented on MaintenanceApi.yaml
> +- name: Maintenance (Unscheduled)
This doesn't line up with the tags called out in the unscheduled maintenance endpoints

2022-05-11 13:13 UTC, GD-ResilienX commented on MaintenanceApi.yaml
> +        - Unscheduled Maintenance
Should line up with the tags set up top (see other issue)

2022-05-11 13:22 UTC, GD-ResilienX approved these changes
👍

2022-05-11 14:06 UTC, AS-resilienx commented
Unscheduled Maintenance -> GET -> should we add a 404 response for an invalid component id?

2022-05-11 14:29 UTC, MS-ResilienX commented
> Unscheduled Maintenance -> GET -> should we add a 404 response for an invalid component id?

What's the precedent? Do we individually validate query parameters?

2022-05-11 14:40 UTC, GD-ResilienX commented on MaintenanceApi.yaml
> +        200:
Needs a 400 bad request for bad query parameters

2022-05-12 15:43 UTC, GD-ResilienX commented on MaintenanceApi.yaml
> +  /maintenance/unscheduled:
Is there a reason that *everything* here is under a maintenance path? The spec already says everything is under api/maintenance/v0?

2022-05-12 18:14 UTC, GD-ResilienX commented on MaintenanceApi.yaml
> +  /maintenance/unscheduled:
This will be handled in future issue

2022-05-12 18:14 UTC, GD-ResilienX approved these changes
Back to approval

2022-05-20 01:31 UTC, merged