Fraihm 2029 maintenance service delete appointment
ResilienX/fraihmwork-api pull request #61
Opened 2022-07-15 19:06 UTC by JF-ResilienX

2022-07-21 12:17 UTC, MS-ResilienX requested changes
The change needs a versioning consideration. The version file also needs updating, so this should be two files.

2022-07-21 14:26 UTC, AS-resilienx requested changes
Have the same comment as @MS-ResilienX  -> the MaintenanceApiChangelist.txt needs to be updated with the new version.

Prior to that, the version of the MitigationApi needs to change as well.

2022-07-21 20:22 UTC, AS-resilienx approved these changes

2022-07-22 12:18 UTC, GD-ResilienX approved these changes

2022-07-22 12:20 UTC, merged