Merge branch 'develop' of https://github.com/ResilienX/fraihmwork-api…
ResilienX/fraihmwork-api pull request #86
Opened 2023-09-05 19:45 UTC by MS-ResilienX

… into #84-Combine-blocklister-FHAIS-API

# Conflicts:
#	FraihmworkHealthAndIntegrityApi.yaml
#	FraihmworkHealthAndIntegrityApiChangelist.txt

2023-09-05 19:47 UTC, MS-ResilienX commented on Deprecated/BlocklistingApi.yaml
This diff isn't very helpful. The two BlocklistingApi* files from develop were merely copied into the Deprecated folder.

2023-09-06 14:18 UTC, BW-ResilienX requested changes

2023-09-06 14:18 UTC, BW-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +  description: Blocklist management apis
To match other tag descriptions.
```suggestion
  description: Blocklist management api endpoints
```

2023-09-06 14:27 UTC, GD-ResilienX requested changes

2023-09-06 14:27 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +                $ref: '#/components/schemas/Response'
Let's toss some 403's here in the blocklister apis, for accuracy and consistency

2023-09-06 14:27 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +      - OAuth2: [fraihmwork.blocklist.read]
I think fraihmwork.blocklist.manage should probably be able to read the blocklist, we moved towards this in the rest of the endpoints in this spec.

2023-09-08 10:59 UTC, BW-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +            fraihmwork.blocklist.manage: Client can modify the blocklist
Should we try to match the language of the component and fault scopes?

2023-09-11 12:41 UTC, BW-ResilienX approved these changes

2023-09-12 13:18 UTC, GD-ResilienX approved these changes

2023-10-04 21:08 UTC, merged