#87: Updating/clarifying descriptions for FHAIS scopes and requests. …
ResilienX/fraihmwork-api pull request #88
Opened 2023-09-11 15:42 UTC by MS-ResilienX

…MitigatorApi: Updating scopes to match FHAIS API scopes.

2023-09-12 15:59 UTC, BW-ResilienX approved these changes

2023-09-15 13:28 UTC, GD-ResilienX requested changes

2023-09-15 13:28 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +      description: This information allows FRAIHMWORK to track basic information about a component. Any extra or custom fields are expected to always be present even if null values are provided at fi
Actually, this is the one action where I don't think there are any limitations on the write vs admin. Creating a new component should always work for both of these scopes, barring any bad requests

2023-09-15 13:28 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +      description: Allows a component to report one or more faults currently affecting the component. Using this endpoint means that the client is not managing their own fault IDs, and the fault will
Same as above - posting a fault doesn't have write vs admin differences

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      description: This call adds a system to the collection of possible mitigations. Returns a UUID upon successful POST. Mitigations having MANUAL resolution must only start in ACCEPTED state. Atte
Same as above - posting a mitigation doesn't have write vs admin differences

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
read, write and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
Read, write, and admin

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      - OAuth2: [fraihmwork.mitigation.read]
```suggestion
      - OAuth2: [fraihmwork.mitigation.read, fraihmwork.mitigation.write, fraihmwork.mitigation.admin]

```

2023-09-15 13:28 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +      description: This information allows FRAIHMWORK to track basic information about a component. Any extra or custom fields are expected to always be present even if null values are provided at fi
```suggestion
      description: This information allows FRAIHMWORK to track basic information about a component. Any extra or custom fields are expected to always be present even if null values are provided at first. Using this endpoint means that the component needs to be registered (under the hood), so a UUID will be created and assigned in the response. 
```

2023-09-15 13:28 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +      description: Allows a component to report one or more faults currently affecting the component. Using this endpoint means that the client is not managing their own fault IDs, and the fault will
```suggestion
      description: Allows a component to report one or more faults currently affecting the component. Using this endpoint means that the client is not managing their own fault IDs, and the fault will require a new tracking UUID (that will be created and assigned in the response).
```

2023-09-15 13:28 UTC, GD-ResilienX commented on MitigationApi.yml
> +      description: This call adds a system to the collection of possible mitigations. Returns a UUID upon successful POST. Mitigations having MANUAL resolution must only start in ACCEPTED state. Atte
```suggestion
      description: This call adds a system to the collection of possible mitigations. Returns a UUID upon successful POST. Mitigations having MANUAL resolution must only start in ACCEPTED state. Attempts to start mitigations in RECOMMENDED state will return a invalid payload code.

```

2023-09-18 15:32 UTC, GD-ResilienX approved these changes

2023-10-13 13:38 UTC, merged