Merging in the mitigator api endpoints, removing subscriber endpoints…
ResilienX/fraihmwork-api pull request #89
Opened 2023-10-04 22:13 UTC by GD-ResilienX

… from original, removed mitigation spec now that it has been merged, blocklister permissions updated to read/write/admin

2023-10-05 22:24 UTC, JF-ResilienX approved these changes

2023-10-06 19:14 UTC, MS-ResilienX requested changes

2023-10-06 19:14 UTC, MS-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
>        description: This call replaces a blocklist entry so that it can be updated. It takes the blocklist UUID as a parameter
```suggestion
      description: This call replaces a blocklist entry so that it can be updated. It takes the blocklist UUID as a parameter.
```

2023-10-06 19:14 UTC, MS-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +          description: Seconds within which a component update is expected from the client. If no update is received, the component will consider the component lifeless.
```suggestion
          description: Seconds within which a component update is expected from the client. If no update is received, the component will consider the component unlively.
```

2023-10-06 19:14 UTC, MS-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
> +            fraihmwork.mitigation.read: Client may read any mitigation that FRAIHMWORK can provide, regardless of creator.
```suggestion
            fraihmwork.mitigation.admin: Client may create, read, update, or delete any mitigation regardless of creator
            fraihmwork.mitigation.write: Client may create new mitigations, but can only update and delete mitigations they create. Client may read all mitigations regardless of creator
            fraihmwork.mitigation.read: Client may read any mitigation that FRAIHMWORK can provide, regardless of creator
```

2023-10-06 19:14 UTC, MS-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
In general, this file has inconsistent use of periods in various places. I don't think it's a big deal, just something I noticed. Shorter descriptions are sentence fragments, and you can get away with no period, but in some cases, there are sentence fragments with periods, too.

I'm ok if we want to just ignore this. Since this is such a big and beautiful API file, I figure I'd raise this.

2023-10-13 20:29 UTC, GD-ResilienX commented on FraihmworkHealthAndIntegrityApi.yaml
Accepted changes, I'm not too picky about it and feel like it probably isn't worth a deep scrub

2023-10-16 18:11 UTC, MS-ResilienX approved these changes

2023-10-16 18:12 UTC, merged